//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mordomo.Client.LoadFormData {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CascadingDropDownNameValue", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class CascadingDropDownNameValue : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string valueField;
        
        private bool isDefaultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string optionTitleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string value {
            get {
                return this.valueField;
            }
            set {
                if ((object.ReferenceEquals(this.valueField, value) != true)) {
                    this.valueField = value;
                    this.RaisePropertyChanged("value");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool isDefaultValue {
            get {
                return this.isDefaultValueField;
            }
            set {
                if ((this.isDefaultValueField.Equals(value) != true)) {
                    this.isDefaultValueField = value;
                    this.RaisePropertyChanged("isDefaultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string optionTitle {
            get {
                return this.optionTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.optionTitleField, value) != true)) {
                    this.optionTitleField = value;
                    this.RaisePropertyChanged("optionTitle");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DropDownData", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class DropDownData : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LoadFormData.LoadFormDataSoap")]
    public interface LoadFormDataSoap {
        
        // CODEGEN: Generating message contract since element name knownCategoryValues from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStates", ReplyAction="*")]
        Mordomo.Client.LoadFormData.GetStatesResponse GetStates(Mordomo.Client.LoadFormData.GetStatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetStates", ReplyAction="*")]
        System.IAsyncResult BeginGetStates(Mordomo.Client.LoadFormData.GetStatesRequest request, System.AsyncCallback callback, object asyncState);
        
        Mordomo.Client.LoadFormData.GetStatesResponse EndGetStates(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name knownCategoryValues from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCities", ReplyAction="*")]
        Mordomo.Client.LoadFormData.GetCitiesResponse GetCities(Mordomo.Client.LoadFormData.GetCitiesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetCities", ReplyAction="*")]
        System.IAsyncResult BeginGetCities(Mordomo.Client.LoadFormData.GetCitiesRequest request, System.AsyncCallback callback, object asyncState);
        
        Mordomo.Client.LoadFormData.GetCitiesResponse EndGetCities(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name promptText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetStates2", ReplyAction="*")]
        Mordomo.Client.LoadFormData.GetStates2Response GetStates2(Mordomo.Client.LoadFormData.GetStates2Request request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetStates2", ReplyAction="*")]
        System.IAsyncResult BeginGetStates2(Mordomo.Client.LoadFormData.GetStates2Request request, System.AsyncCallback callback, object asyncState);
        
        Mordomo.Client.LoadFormData.GetStates2Response EndGetStates2(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name promptText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCities2", ReplyAction="*")]
        Mordomo.Client.LoadFormData.GetCities2Response GetCities2(Mordomo.Client.LoadFormData.GetCities2Request request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetCities2", ReplyAction="*")]
        System.IAsyncResult BeginGetCities2(Mordomo.Client.LoadFormData.GetCities2Request request, System.AsyncCallback callback, object asyncState);
        
        Mordomo.Client.LoadFormData.GetCities2Response EndGetCities2(System.IAsyncResult result);
        
        // CODEGEN: Generating message contract since element name promptText from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAndressTypes", ReplyAction="*")]
        Mordomo.Client.LoadFormData.GetAndressTypesResponse GetAndressTypes(Mordomo.Client.LoadFormData.GetAndressTypesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetAndressTypes", ReplyAction="*")]
        System.IAsyncResult BeginGetAndressTypes(Mordomo.Client.LoadFormData.GetAndressTypesRequest request, System.AsyncCallback callback, object asyncState);
        
        Mordomo.Client.LoadFormData.GetAndressTypesResponse EndGetAndressTypes(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStates", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetStatesRequestBody Body;
        
        public GetStatesRequest() {
        }
        
        public GetStatesRequest(Mordomo.Client.LoadFormData.GetStatesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string knownCategoryValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string category;
        
        public GetStatesRequestBody() {
        }
        
        public GetStatesRequestBody(string knownCategoryValues, string category) {
            this.knownCategoryValues = knownCategoryValues;
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStatesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetStatesResponseBody Body;
        
        public GetStatesResponse() {
        }
        
        public GetStatesResponse(Mordomo.Client.LoadFormData.GetStatesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStatesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] GetStatesResult;
        
        public GetStatesResponseBody() {
        }
        
        public GetStatesResponseBody(Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] GetStatesResult) {
            this.GetStatesResult = GetStatesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCities", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetCitiesRequestBody Body;
        
        public GetCitiesRequest() {
        }
        
        public GetCitiesRequest(Mordomo.Client.LoadFormData.GetCitiesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string knownCategoryValues;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string category;
        
        public GetCitiesRequestBody() {
        }
        
        public GetCitiesRequestBody(string knownCategoryValues, string category) {
            this.knownCategoryValues = knownCategoryValues;
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCitiesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCitiesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetCitiesResponseBody Body;
        
        public GetCitiesResponse() {
        }
        
        public GetCitiesResponse(Mordomo.Client.LoadFormData.GetCitiesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCitiesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] GetCitiesResult;
        
        public GetCitiesResponseBody() {
        }
        
        public GetCitiesResponseBody(Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] GetCitiesResult) {
            this.GetCitiesResult = GetCitiesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStates2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStates2", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetStates2RequestBody Body;
        
        public GetStates2Request() {
        }
        
        public GetStates2Request(Mordomo.Client.LoadFormData.GetStates2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStates2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string promptText;
        
        public GetStates2RequestBody() {
        }
        
        public GetStates2RequestBody(string promptText) {
            this.promptText = promptText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStates2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStates2Response", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetStates2ResponseBody Body;
        
        public GetStates2Response() {
        }
        
        public GetStates2Response(Mordomo.Client.LoadFormData.GetStates2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStates2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mordomo.Client.LoadFormData.DropDownData[] GetStates2Result;
        
        public GetStates2ResponseBody() {
        }
        
        public GetStates2ResponseBody(Mordomo.Client.LoadFormData.DropDownData[] GetStates2Result) {
            this.GetStates2Result = GetStates2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCities2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCities2", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetCities2RequestBody Body;
        
        public GetCities2Request() {
        }
        
        public GetCities2Request(Mordomo.Client.LoadFormData.GetCities2RequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCities2RequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int stateId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string promptText;
        
        public GetCities2RequestBody() {
        }
        
        public GetCities2RequestBody(int stateId, string promptText) {
            this.stateId = stateId;
            this.promptText = promptText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCities2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCities2Response", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetCities2ResponseBody Body;
        
        public GetCities2Response() {
        }
        
        public GetCities2Response(Mordomo.Client.LoadFormData.GetCities2ResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCities2ResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mordomo.Client.LoadFormData.DropDownData[] GetCities2Result;
        
        public GetCities2ResponseBody() {
        }
        
        public GetCities2ResponseBody(Mordomo.Client.LoadFormData.DropDownData[] GetCities2Result) {
            this.GetCities2Result = GetCities2Result;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAndressTypesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAndressTypes", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetAndressTypesRequestBody Body;
        
        public GetAndressTypesRequest() {
        }
        
        public GetAndressTypesRequest(Mordomo.Client.LoadFormData.GetAndressTypesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAndressTypesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string promptText;
        
        public GetAndressTypesRequestBody() {
        }
        
        public GetAndressTypesRequestBody(string promptText) {
            this.promptText = promptText;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAndressTypesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAndressTypesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Mordomo.Client.LoadFormData.GetAndressTypesResponseBody Body;
        
        public GetAndressTypesResponse() {
        }
        
        public GetAndressTypesResponse(Mordomo.Client.LoadFormData.GetAndressTypesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAndressTypesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Mordomo.Client.LoadFormData.DropDownData[] GetAndressTypesResult;
        
        public GetAndressTypesResponseBody() {
        }
        
        public GetAndressTypesResponseBody(Mordomo.Client.LoadFormData.DropDownData[] GetAndressTypesResult) {
            this.GetAndressTypesResult = GetAndressTypesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LoadFormDataSoapChannel : Mordomo.Client.LoadFormData.LoadFormDataSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mordomo.Client.LoadFormData.CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCitiesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCitiesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mordomo.Client.LoadFormData.CascadingDropDownNameValue[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStates2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStates2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mordomo.Client.LoadFormData.DropDownData[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mordomo.Client.LoadFormData.DropDownData[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetCities2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetCities2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mordomo.Client.LoadFormData.DropDownData[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mordomo.Client.LoadFormData.DropDownData[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetAndressTypesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetAndressTypesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public Mordomo.Client.LoadFormData.DropDownData[] Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((Mordomo.Client.LoadFormData.DropDownData[])(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LoadFormDataSoapClient : System.ServiceModel.ClientBase<Mordomo.Client.LoadFormData.LoadFormDataSoap>, Mordomo.Client.LoadFormData.LoadFormDataSoap {
        
        private BeginOperationDelegate onBeginGetStatesDelegate;
        
        private EndOperationDelegate onEndGetStatesDelegate;
        
        private System.Threading.SendOrPostCallback onGetStatesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCitiesDelegate;
        
        private EndOperationDelegate onEndGetCitiesDelegate;
        
        private System.Threading.SendOrPostCallback onGetCitiesCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStates2Delegate;
        
        private EndOperationDelegate onEndGetStates2Delegate;
        
        private System.Threading.SendOrPostCallback onGetStates2CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetCities2Delegate;
        
        private EndOperationDelegate onEndGetCities2Delegate;
        
        private System.Threading.SendOrPostCallback onGetCities2CompletedDelegate;
        
        private BeginOperationDelegate onBeginGetAndressTypesDelegate;
        
        private EndOperationDelegate onEndGetAndressTypesDelegate;
        
        private System.Threading.SendOrPostCallback onGetAndressTypesCompletedDelegate;
        
        public LoadFormDataSoapClient() {
        }
        
        public LoadFormDataSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LoadFormDataSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadFormDataSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LoadFormDataSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public event System.EventHandler<GetStatesCompletedEventArgs> GetStatesCompleted;
        
        public event System.EventHandler<GetCitiesCompletedEventArgs> GetCitiesCompleted;
        
        public event System.EventHandler<GetStates2CompletedEventArgs> GetStates2Completed;
        
        public event System.EventHandler<GetCities2CompletedEventArgs> GetCities2Completed;
        
        public event System.EventHandler<GetAndressTypesCompletedEventArgs> GetAndressTypesCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetStatesResponse Mordomo.Client.LoadFormData.LoadFormDataSoap.GetStates(Mordomo.Client.LoadFormData.GetStatesRequest request) {
            return base.Channel.GetStates(request);
        }
        
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] GetStates(string knownCategoryValues, string category) {
            Mordomo.Client.LoadFormData.GetStatesRequest inValue = new Mordomo.Client.LoadFormData.GetStatesRequest();
            inValue.Body = new Mordomo.Client.LoadFormData.GetStatesRequestBody();
            inValue.Body.knownCategoryValues = knownCategoryValues;
            inValue.Body.category = category;
            Mordomo.Client.LoadFormData.GetStatesResponse retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).GetStates(inValue);
            return retVal.Body.GetStatesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mordomo.Client.LoadFormData.LoadFormDataSoap.BeginGetStates(Mordomo.Client.LoadFormData.GetStatesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStates(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetStates(string knownCategoryValues, string category, System.AsyncCallback callback, object asyncState) {
            Mordomo.Client.LoadFormData.GetStatesRequest inValue = new Mordomo.Client.LoadFormData.GetStatesRequest();
            inValue.Body = new Mordomo.Client.LoadFormData.GetStatesRequestBody();
            inValue.Body.knownCategoryValues = knownCategoryValues;
            inValue.Body.category = category;
            return ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).BeginGetStates(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetStatesResponse Mordomo.Client.LoadFormData.LoadFormDataSoap.EndGetStates(System.IAsyncResult result) {
            return base.Channel.EndGetStates(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] EndGetStates(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.GetStatesResponse retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).EndGetStates(result);
            return retVal.Body.GetStatesResult;
        }
        
        private System.IAsyncResult OnBeginGetStates(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string knownCategoryValues = ((string)(inValues[0]));
            string category = ((string)(inValues[1]));
            return this.BeginGetStates(knownCategoryValues, category, callback, asyncState);
        }
        
        private object[] OnEndGetStates(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] retVal = this.EndGetStates(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStatesCompleted(object state) {
            if ((this.GetStatesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStatesCompleted(this, new GetStatesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStatesAsync(string knownCategoryValues, string category) {
            this.GetStatesAsync(knownCategoryValues, category, null);
        }
        
        public void GetStatesAsync(string knownCategoryValues, string category, object userState) {
            if ((this.onBeginGetStatesDelegate == null)) {
                this.onBeginGetStatesDelegate = new BeginOperationDelegate(this.OnBeginGetStates);
            }
            if ((this.onEndGetStatesDelegate == null)) {
                this.onEndGetStatesDelegate = new EndOperationDelegate(this.OnEndGetStates);
            }
            if ((this.onGetStatesCompletedDelegate == null)) {
                this.onGetStatesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStatesCompleted);
            }
            base.InvokeAsync(this.onBeginGetStatesDelegate, new object[] {
                        knownCategoryValues,
                        category}, this.onEndGetStatesDelegate, this.onGetStatesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetCitiesResponse Mordomo.Client.LoadFormData.LoadFormDataSoap.GetCities(Mordomo.Client.LoadFormData.GetCitiesRequest request) {
            return base.Channel.GetCities(request);
        }
        
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] GetCities(string knownCategoryValues, string category) {
            Mordomo.Client.LoadFormData.GetCitiesRequest inValue = new Mordomo.Client.LoadFormData.GetCitiesRequest();
            inValue.Body = new Mordomo.Client.LoadFormData.GetCitiesRequestBody();
            inValue.Body.knownCategoryValues = knownCategoryValues;
            inValue.Body.category = category;
            Mordomo.Client.LoadFormData.GetCitiesResponse retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).GetCities(inValue);
            return retVal.Body.GetCitiesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mordomo.Client.LoadFormData.LoadFormDataSoap.BeginGetCities(Mordomo.Client.LoadFormData.GetCitiesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCities(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCities(string knownCategoryValues, string category, System.AsyncCallback callback, object asyncState) {
            Mordomo.Client.LoadFormData.GetCitiesRequest inValue = new Mordomo.Client.LoadFormData.GetCitiesRequest();
            inValue.Body = new Mordomo.Client.LoadFormData.GetCitiesRequestBody();
            inValue.Body.knownCategoryValues = knownCategoryValues;
            inValue.Body.category = category;
            return ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).BeginGetCities(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetCitiesResponse Mordomo.Client.LoadFormData.LoadFormDataSoap.EndGetCities(System.IAsyncResult result) {
            return base.Channel.EndGetCities(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] EndGetCities(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.GetCitiesResponse retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).EndGetCities(result);
            return retVal.Body.GetCitiesResult;
        }
        
        private System.IAsyncResult OnBeginGetCities(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string knownCategoryValues = ((string)(inValues[0]));
            string category = ((string)(inValues[1]));
            return this.BeginGetCities(knownCategoryValues, category, callback, asyncState);
        }
        
        private object[] OnEndGetCities(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.CascadingDropDownNameValue[] retVal = this.EndGetCities(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCitiesCompleted(object state) {
            if ((this.GetCitiesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCitiesCompleted(this, new GetCitiesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCitiesAsync(string knownCategoryValues, string category) {
            this.GetCitiesAsync(knownCategoryValues, category, null);
        }
        
        public void GetCitiesAsync(string knownCategoryValues, string category, object userState) {
            if ((this.onBeginGetCitiesDelegate == null)) {
                this.onBeginGetCitiesDelegate = new BeginOperationDelegate(this.OnBeginGetCities);
            }
            if ((this.onEndGetCitiesDelegate == null)) {
                this.onEndGetCitiesDelegate = new EndOperationDelegate(this.OnEndGetCities);
            }
            if ((this.onGetCitiesCompletedDelegate == null)) {
                this.onGetCitiesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCitiesCompleted);
            }
            base.InvokeAsync(this.onBeginGetCitiesDelegate, new object[] {
                        knownCategoryValues,
                        category}, this.onEndGetCitiesDelegate, this.onGetCitiesCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetStates2Response Mordomo.Client.LoadFormData.LoadFormDataSoap.GetStates2(Mordomo.Client.LoadFormData.GetStates2Request request) {
            return base.Channel.GetStates2(request);
        }
        
        public Mordomo.Client.LoadFormData.DropDownData[] GetStates2(string promptText) {
            Mordomo.Client.LoadFormData.GetStates2Request inValue = new Mordomo.Client.LoadFormData.GetStates2Request();
            inValue.Body = new Mordomo.Client.LoadFormData.GetStates2RequestBody();
            inValue.Body.promptText = promptText;
            Mordomo.Client.LoadFormData.GetStates2Response retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).GetStates2(inValue);
            return retVal.Body.GetStates2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mordomo.Client.LoadFormData.LoadFormDataSoap.BeginGetStates2(Mordomo.Client.LoadFormData.GetStates2Request request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetStates2(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetStates2(string promptText, System.AsyncCallback callback, object asyncState) {
            Mordomo.Client.LoadFormData.GetStates2Request inValue = new Mordomo.Client.LoadFormData.GetStates2Request();
            inValue.Body = new Mordomo.Client.LoadFormData.GetStates2RequestBody();
            inValue.Body.promptText = promptText;
            return ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).BeginGetStates2(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetStates2Response Mordomo.Client.LoadFormData.LoadFormDataSoap.EndGetStates2(System.IAsyncResult result) {
            return base.Channel.EndGetStates2(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Mordomo.Client.LoadFormData.DropDownData[] EndGetStates2(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.GetStates2Response retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).EndGetStates2(result);
            return retVal.Body.GetStates2Result;
        }
        
        private System.IAsyncResult OnBeginGetStates2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string promptText = ((string)(inValues[0]));
            return this.BeginGetStates2(promptText, callback, asyncState);
        }
        
        private object[] OnEndGetStates2(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.DropDownData[] retVal = this.EndGetStates2(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStates2Completed(object state) {
            if ((this.GetStates2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStates2Completed(this, new GetStates2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStates2Async(string promptText) {
            this.GetStates2Async(promptText, null);
        }
        
        public void GetStates2Async(string promptText, object userState) {
            if ((this.onBeginGetStates2Delegate == null)) {
                this.onBeginGetStates2Delegate = new BeginOperationDelegate(this.OnBeginGetStates2);
            }
            if ((this.onEndGetStates2Delegate == null)) {
                this.onEndGetStates2Delegate = new EndOperationDelegate(this.OnEndGetStates2);
            }
            if ((this.onGetStates2CompletedDelegate == null)) {
                this.onGetStates2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStates2Completed);
            }
            base.InvokeAsync(this.onBeginGetStates2Delegate, new object[] {
                        promptText}, this.onEndGetStates2Delegate, this.onGetStates2CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetCities2Response Mordomo.Client.LoadFormData.LoadFormDataSoap.GetCities2(Mordomo.Client.LoadFormData.GetCities2Request request) {
            return base.Channel.GetCities2(request);
        }
        
        public Mordomo.Client.LoadFormData.DropDownData[] GetCities2(int stateId, string promptText) {
            Mordomo.Client.LoadFormData.GetCities2Request inValue = new Mordomo.Client.LoadFormData.GetCities2Request();
            inValue.Body = new Mordomo.Client.LoadFormData.GetCities2RequestBody();
            inValue.Body.stateId = stateId;
            inValue.Body.promptText = promptText;
            Mordomo.Client.LoadFormData.GetCities2Response retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).GetCities2(inValue);
            return retVal.Body.GetCities2Result;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mordomo.Client.LoadFormData.LoadFormDataSoap.BeginGetCities2(Mordomo.Client.LoadFormData.GetCities2Request request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetCities2(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetCities2(int stateId, string promptText, System.AsyncCallback callback, object asyncState) {
            Mordomo.Client.LoadFormData.GetCities2Request inValue = new Mordomo.Client.LoadFormData.GetCities2Request();
            inValue.Body = new Mordomo.Client.LoadFormData.GetCities2RequestBody();
            inValue.Body.stateId = stateId;
            inValue.Body.promptText = promptText;
            return ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).BeginGetCities2(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetCities2Response Mordomo.Client.LoadFormData.LoadFormDataSoap.EndGetCities2(System.IAsyncResult result) {
            return base.Channel.EndGetCities2(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Mordomo.Client.LoadFormData.DropDownData[] EndGetCities2(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.GetCities2Response retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).EndGetCities2(result);
            return retVal.Body.GetCities2Result;
        }
        
        private System.IAsyncResult OnBeginGetCities2(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int stateId = ((int)(inValues[0]));
            string promptText = ((string)(inValues[1]));
            return this.BeginGetCities2(stateId, promptText, callback, asyncState);
        }
        
        private object[] OnEndGetCities2(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.DropDownData[] retVal = this.EndGetCities2(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetCities2Completed(object state) {
            if ((this.GetCities2Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetCities2Completed(this, new GetCities2CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetCities2Async(int stateId, string promptText) {
            this.GetCities2Async(stateId, promptText, null);
        }
        
        public void GetCities2Async(int stateId, string promptText, object userState) {
            if ((this.onBeginGetCities2Delegate == null)) {
                this.onBeginGetCities2Delegate = new BeginOperationDelegate(this.OnBeginGetCities2);
            }
            if ((this.onEndGetCities2Delegate == null)) {
                this.onEndGetCities2Delegate = new EndOperationDelegate(this.OnEndGetCities2);
            }
            if ((this.onGetCities2CompletedDelegate == null)) {
                this.onGetCities2CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetCities2Completed);
            }
            base.InvokeAsync(this.onBeginGetCities2Delegate, new object[] {
                        stateId,
                        promptText}, this.onEndGetCities2Delegate, this.onGetCities2CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetAndressTypesResponse Mordomo.Client.LoadFormData.LoadFormDataSoap.GetAndressTypes(Mordomo.Client.LoadFormData.GetAndressTypesRequest request) {
            return base.Channel.GetAndressTypes(request);
        }
        
        public Mordomo.Client.LoadFormData.DropDownData[] GetAndressTypes(string promptText) {
            Mordomo.Client.LoadFormData.GetAndressTypesRequest inValue = new Mordomo.Client.LoadFormData.GetAndressTypesRequest();
            inValue.Body = new Mordomo.Client.LoadFormData.GetAndressTypesRequestBody();
            inValue.Body.promptText = promptText;
            Mordomo.Client.LoadFormData.GetAndressTypesResponse retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).GetAndressTypes(inValue);
            return retVal.Body.GetAndressTypesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Mordomo.Client.LoadFormData.LoadFormDataSoap.BeginGetAndressTypes(Mordomo.Client.LoadFormData.GetAndressTypesRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetAndressTypes(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public System.IAsyncResult BeginGetAndressTypes(string promptText, System.AsyncCallback callback, object asyncState) {
            Mordomo.Client.LoadFormData.GetAndressTypesRequest inValue = new Mordomo.Client.LoadFormData.GetAndressTypesRequest();
            inValue.Body = new Mordomo.Client.LoadFormData.GetAndressTypesRequestBody();
            inValue.Body.promptText = promptText;
            return ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).BeginGetAndressTypes(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Mordomo.Client.LoadFormData.GetAndressTypesResponse Mordomo.Client.LoadFormData.LoadFormDataSoap.EndGetAndressTypes(System.IAsyncResult result) {
            return base.Channel.EndGetAndressTypes(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public Mordomo.Client.LoadFormData.DropDownData[] EndGetAndressTypes(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.GetAndressTypesResponse retVal = ((Mordomo.Client.LoadFormData.LoadFormDataSoap)(this)).EndGetAndressTypes(result);
            return retVal.Body.GetAndressTypesResult;
        }
        
        private System.IAsyncResult OnBeginGetAndressTypes(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string promptText = ((string)(inValues[0]));
            return this.BeginGetAndressTypes(promptText, callback, asyncState);
        }
        
        private object[] OnEndGetAndressTypes(System.IAsyncResult result) {
            Mordomo.Client.LoadFormData.DropDownData[] retVal = this.EndGetAndressTypes(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetAndressTypesCompleted(object state) {
            if ((this.GetAndressTypesCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetAndressTypesCompleted(this, new GetAndressTypesCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetAndressTypesAsync(string promptText) {
            this.GetAndressTypesAsync(promptText, null);
        }
        
        public void GetAndressTypesAsync(string promptText, object userState) {
            if ((this.onBeginGetAndressTypesDelegate == null)) {
                this.onBeginGetAndressTypesDelegate = new BeginOperationDelegate(this.OnBeginGetAndressTypes);
            }
            if ((this.onEndGetAndressTypesDelegate == null)) {
                this.onEndGetAndressTypesDelegate = new EndOperationDelegate(this.OnEndGetAndressTypes);
            }
            if ((this.onGetAndressTypesCompletedDelegate == null)) {
                this.onGetAndressTypesCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetAndressTypesCompleted);
            }
            base.InvokeAsync(this.onBeginGetAndressTypesDelegate, new object[] {
                        promptText}, this.onEndGetAndressTypesDelegate, this.onGetAndressTypesCompletedDelegate, userState);
        }
    }
}
